/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingPageAdvogadosRouteImport } from './routes/landing-page-advogados'
import { Route as LandingPageAcademiasRouteImport } from './routes/landing-page-academias'
import { Route as IndexRouteImport } from './routes/index'

const LandingPageAdvogadosRoute = LandingPageAdvogadosRouteImport.update({
  id: '/landing-page-advogados',
  path: '/landing-page-advogados',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageAcademiasRoute = LandingPageAcademiasRouteImport.update({
  id: '/landing-page-academias',
  path: '/landing-page-academias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing-page-academias': typeof LandingPageAcademiasRoute
  '/landing-page-advogados': typeof LandingPageAdvogadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing-page-academias': typeof LandingPageAcademiasRoute
  '/landing-page-advogados': typeof LandingPageAdvogadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing-page-academias': typeof LandingPageAcademiasRoute
  '/landing-page-advogados': typeof LandingPageAdvogadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landing-page-academias' | '/landing-page-advogados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landing-page-academias' | '/landing-page-advogados'
  id: '__root__' | '/' | '/landing-page-academias' | '/landing-page-advogados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingPageAcademiasRoute: typeof LandingPageAcademiasRoute
  LandingPageAdvogadosRoute: typeof LandingPageAdvogadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing-page-advogados': {
      id: '/landing-page-advogados'
      path: '/landing-page-advogados'
      fullPath: '/landing-page-advogados'
      preLoaderRoute: typeof LandingPageAdvogadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page-academias': {
      id: '/landing-page-academias'
      path: '/landing-page-academias'
      fullPath: '/landing-page-academias'
      preLoaderRoute: typeof LandingPageAcademiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingPageAcademiasRoute: LandingPageAcademiasRoute,
  LandingPageAdvogadosRoute: LandingPageAdvogadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
